### PR TITLE
Fixes for #9

### LINKED ISSUE #9: Cannot upload files with the same basename from different directories
https://github.com/OpenDroneMap/PyODM/blob/master/pyodm/api.py#L299

Reported https://community.opendronemap.org/t/clusterodm-distributed-split-merge-directory-file-naming/2656

### PR DESCRIPTION
**Pull request by zachaller**
I think this should fix the issue with same file collisions. This should close #9

### CODE REVIEW

**Comment by pierotofy** [comment]
Hi @zachaller, thank you for the proposed fix!

Two things to address before merging:
 - pathlib is not available in Python 2.x (ODM depends on Python 2.x)
 - This logic would break any GCP file passed as input (it would throw off the filename references). Ideally, a GCP should first be checked (is there a GCP?), if there is AND there are duplicate filenames that are referenced in the GCP, the program should raise an exception. If there are no duplicates, then filenames should be preserved. If there are no GCPs, the logic here is OK (and perhaps it would be easier to just append a "-1,-2,-3,-N" suffix to the filename instead of a full UUID).

The `gcp.py` class could be useful here https://github.com/OpenDroneMap/ODM/blob/master/opendm/gcp.py

**Review by spifftek70 — COMMENTED** [review]
This doesn't account for datasets with `gcp_list.txt` files.  If using GCPs for georeferencing, this will break that process as the images are listed on that document under the original file name.  Cc - @pierotofy 

Nevermind, you caught it.

**Comment by zachaller** [comment]
Two questions?

1. So looking at NodeODM it seems if there is a txt file or a seeds.zip in the list of files it contains GCP's so it would seem that I could use that to decide not to rename the files base on those two things and then also do the check for duplicates and throw an error?

2. On the build instructions for PyODM (https://github.com/OpenDroneMap/PyODM#building-the-documentation) it mentions requiring python3 to build is that correct or is this ticket correct in that python3 should not be used for PyODM?

**Comment by pierotofy** [comment]
1. I would check for the presence of a .txt file in the image list (don't worry about the seed.zip file). If there's one, it's likely a GCP, should be parsed and see if any of the filenames referenced in the GCP are also in the image list.

2. PyODM is being used in both ODM (Python 2.x) and WebODM (Python 3.x), so the code needs to work across both 2.x and 3.x.

**Comment by pierotofy** [comment]
@zachaller do you need more time for this?

**Comment by pierotofy** [comment]
Closing due to inactivity.

**Pull request closed without merging**
