### PR TITLE
Support for image URLs with access tokens

### PR DESCRIPTION
**Pull request by jamesfisher-geo**
Added a regex to identify access tokens appended to image URLs. If found, the image filename is extracted from the URL accordingly.

### CODE REVIEW

**Review by pierotofy — APPROVED** [review]
Thanks @jamesfisher-gis !

**Comment by jamesfisher-geo** [comment]
Thank you @pierotofy for developing ODM!

**Comment by jamesfisher-geo** [comment]
Hi @pierotofy, just wondering if you have plans to publish the updated PyODM to PyPI? (I assume this is not something I can do) I am working with PyODM on docker and my image does not like pip installing from my GitHub fork 🥴

**Comment by pierotofy** [comment]
Just updated it, the latest version is on PyPI (1.5.10).

**Comment by jamesfisher-geo** [comment]
Thank you!

**Pull request merged**
